export default [
  {
    id: 1,
    name: "Maria",
    title: "Manager",
    salary: "1000",
    phone: "044012345",
    email: "maria@gmail.com",
    animal: "Lion",
  },
  {
    id: 2,
    name: "Alex",
    title: "Security Officer",
    salary: "1800",
    phone: "045678901",
    email: "alex.smith@example.com",
    animal: "Wolf",
  },
  {
    id: 3,
    name: "Sofia",
    title: "Barista",
    salary: "1500",
    phone: "040123456",
    email: "sofia.laine@gmail.com",
    animal: "Cat",
  },
  {
    id: 4,
    name: "Liam",
    title: "Developer",
    salary: "2000",
    phone: "046789012",
    email: "liam@example.com",
    animal: "Eagle",
  },
  {
    id: 5,
    name: "Emma",
    title: "Designer",
    salary: "1700",
    phone: "043456789",
    email: "Emma@example.com",
    animal: "Dolphin",
  },
];
